### ISSUE TITLE
解析异常

### ISSUE THREAD

**Issue by he852100** [yetrun/json5-to-table#30]
```JS
Error: 矩阵访问越界：[0, 0]
    at c._calcIndexInParent (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:6110)
    at c.setVal (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:5986)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:895)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:811)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:544)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:877)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:811)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:544)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:877)
    at t (C:\Users\he123\AppData\Roaming\npm\node_modules\json5-to-table\dist\bundle.js:1:811)
````
[123456.zip](https://github.com/yetrun/json5-to-table/files/7113228/123456.zip)

**Comment by run27017** [comment]
找到原因了，修复起来尚需些时日。

不过我观察到你的数据是无限递归的，不适合用表格展示啊。至少不适合用我的工具。

**Comment by run27017** [comment]
此问题已修复，使用版本 1.0.8.

**Comment by yetrun** [comment]
不好意思说错，是版本 0.1.8
